### ISSUE TITLE
ArgumentException when trying to save surround profile

### ISSUE THREAD

**Issue by Lukazoid** [terrymacdonald/DisplayMagician#188]
Using DisplayMagician v2.5.0

I have 3 monitors in horizontal wide configured in NVidia surround mode at 5760x1080 resolution, from Left to Right the individual monitor resolutions are are 1920x1080, 2560x1440, 1920x1080.

When I attempt to save this configuration DisplayMagician encounters the following exception:

> ************** Exception Text **************
> System.ArgumentException: Parameter is not valid.
>    at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
>    at DisplayMagicianShared.ProfileIcon.ToTightestBitmap(PixelFormat format)
>    at DisplayMagicianShared.ProfileItem.get_ProfileTightestBitmap()
>    at DisplayMagician.UIForms.DisplayProfileForm.btn_save_as_Click(Object sender, EventArgs e)
>    at System.Windows.Forms.Control.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>    at System.Windows.Forms.Button.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I assume there is some issue in calculating the bounding box for the profile icon.

**Comment by Lukazoid** [comment]
Have ran latest from source control, appears this issue has been resolved at some point.
