### ISSUE TITLE
DisplayMagician crashing on load

### ISSUE THREAD

**Issue by mjbarr** [terrymacdonald/DisplayMagician#198]
Hi, 

Every time I try to load Display Magician, I get the message about removing profiles and renewing them for Windows 11. Then I get the loading games dialog, the icon appears in the task area beside the clock and then it disappears.

My system has an AMD Ryzen 5600x and NVidia RTX 3060ti.

I found the log file which shows the following:

`2023-02-23 16:09:16.7818|INFO|DisplayMagician.Program|Program/Main: Starting DisplayMagician v2.5.0.352|
2023-02-23 16:09:16.8298|INFO|DisplayMagician.Program|Program/Main: This is an upgrade from an earlier DisplayMagician Display Profile format to the current DisplayMagician Display Profile format, so it requires the user manual recreate the display profiles.|
2023-02-23 16:09:27.6635|ERROR|DisplayMagician.Program|TaskBarLayout/GetAllCurrentTaskBarPositions: Taskbar read #1 from registry didn't work.|
2023-02-23 16:09:27.7453|WARN|DisplayMagician.Program|NVIDIALibrary/GetNVIDIADisplayConfig: The returned Mosaic Topology Group #1 is NOT VALID and cannot be used.|
2023-02-23 16:09:27.7453|WARN|DisplayMagician.Program|NVIDIALibrary/GetNVIDIADisplayConfig: The returned Mosaic Topology Group #1 is MISSING THE GPU it was created with.|
2023-02-23 16:09:27.7453|WARN|DisplayMagician.Program|NVIDIALibrary/GetNVIDIADisplayConfig: The returned Mosaic Topology Group #1 is MISSING ONE OR MORE DISPLAYS it was created with.|
2023-02-23 16:09:27.9294|WARN|DisplayMagician.Program|NVIDIALibrary/GetNVIDIADisplayConfig: The requested action cannot be performed without Mosaic being enabled. NvAPI_Mosaic_GetDisplayViewportsByResolution() returned error code NVAPI_MOSAIC_NOT_ACTIVE|
2023-02-23 16:09:28.1056|WARN|DisplayMagician.Program|NVIDIALibrary/GetNVIDIADisplayConfig: A miscellaneous error occurred. NvAPI_Disp_ColorControl() returned error code NVAPI_ERROR.|
2023-02-23 16:09:28.1076|WARN|DisplayMagician.Program|NVIDIALibrary/GetNVIDIADisplayConfig: A miscellaneous error occurred. NvAPI_Disp_ColorControl() returned error code NVAPI_ERROR.|
2023-02-23 16:09:28.1076|WARN|DisplayMagician.Program|NVIDIALibrary/GetNVIDIADisplayConfig: A miscellaneous error occurred. NvAPI_Disp_ColorControl() returned error code NVAPI_ERROR.|
2023-02-23 16:09:28.1076|WARN|DisplayMagician.Program|NVIDIALibrary/GetNVIDIADisplayConfig: A miscellaneous error occurred. NvAPI_Disp_ColorControl() returned error code NVAPI_ERROR.|
2023-02-23 16:09:28.4083|WARN|DisplayMagician.Program|NVIDIALibrary/GetNVIDIADisplayConfig: The returned Mosaic Topology Group #1 is NOT VALID and cannot be used.|
2023-02-23 16:09:28.4083|WARN|DisplayMagician.Program|NVIDIALibrary/GetNVIDIADisplayConfig: The returned Mosaic Topology Group #1 is MISSING THE GPU it was created with.|
2023-02-23 16:09:28.4083|WARN|DisplayMagician.Program|NVIDIALibrary/GetNVIDIADisplayConfig: The returned Mosaic Topology Group #1 is MISSING ONE OR MORE DISPLAYS it was created with.|
2023-02-23 16:09:28.5620|WARN|DisplayMagician.Program|NVIDIALibrary/GetNVIDIADisplayConfig: The requested action cannot be performed without Mosaic being enabled. NvAPI_Mosaic_GetDisplayViewportsByResolution() returned error code NVAPI_MOSAIC_NOT_ACTIVE|
2023-02-23 16:09:28.6871|WARN|DisplayMagician.Program|NVIDIALibrary/GetNVIDIADisplayConfig: A miscellaneous error occurred. NvAPI_Disp_ColorControl() returned error code NVAPI_ERROR.|
2023-02-23 16:09:28.6871|WARN|DisplayMagician.Program|NVIDIALibrary/GetNVIDIADisplayConfig: A miscellaneous error occurred. NvAPI_Disp_ColorControl() returned error code NVAPI_ERROR.|
2023-02-23 16:09:28.6871|WARN|DisplayMagician.Program|NVIDIALibrary/GetNVIDIADisplayConfig: A miscellaneous error occurred. NvAPI_Disp_ColorControl() returned error code NVAPI_ERROR.|
2023-02-23 16:09:28.6871|WARN|DisplayMagician.Program|NVIDIALibrary/GetNVIDIADisplayConfig: A miscellaneous error occurred. NvAPI_Disp_ColorControl() returned error code NVAPI_ERROR.|
2023-02-23 16:09:28.9008|INFO|DisplayMagician.Program|Program/Main: Leaving DisplayMagician to detect the best Video Library to use.|
2023-02-23 16:09:28.9083|INFO|DisplayMagician.Program|Program/Main: Leaving DisplayMagician to detect the best Video Library to use.|
2023-02-23 16:09:28.9083|INFO|DisplayMagician.Program|Program/Main: Leaving DisplayMagician to detect the best Video Library to use.|
2023-02-23 16:09:28.9083|INFO|DisplayMagician.Program|Program/Main: Leaving DisplayMagician to detect the best Video Library to use.|
2023-02-23 16:09:29.1124|INFO|DisplayMagician.Program|Program/Main: Leaving DisplayMagician to detect the best Video Library to use.|
2023-02-23 16:09:29.1124|INFO|DisplayMagician.Program|Program/Main: Starting Normally...|
2023-02-23 16:09:29.1124|INFO|DisplayMagician.GameLibraries.SteamLibrary|SteamLibrary/SteamLibrary: Steam library is installed in C:\Program Files (x86)\Steam. Found C:\Program Files (x86)\Steam\steam.exe|
2023-02-23 16:09:29.1239|INFO|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/UplayLibrary: Uplay library is not installed!|
2023-02-23 16:09:29.1239|INFO|DisplayMagician.GameLibraries.OriginLibrary|OriginLibrary/OriginLibrary: Origin library is installed in . Found C:\Program Files\Electronic Arts\EA Desktop\EA Desktop\EADesktop.exe|
2023-02-23 16:09:29.1239|INFO|DisplayMagician.GameLibraries.EpicLibrary|EpicLibrary/EpicLibrary: Epic library is installed in C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win64. Found C:/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win64/EpicGamesLauncher.exe|
2023-02-23 16:09:29.1239|INFO|DisplayMagician.GameLibraries.GogLibrary|GogLibrary/GogLibrary: GOG library is not installed!|
2023-02-23 16:09:29.1239|INFO|DisplayMagician.GameLibraries.GameLibrary|Program/LoadGamesInBackground: Uplay not installed.|
2023-02-23 16:09:29.1239|INFO|DisplayMagician.GameLibraries.GameLibrary|Program/LoadGamesInBackground: Loading Installed Origin Games|
2023-02-23 16:09:29.1239|INFO|DisplayMagician.GameLibraries.GameLibrary|Program/LoadGamesInBackground: Loading Installed Steam Games|
2023-02-23 16:09:29.1239|INFO|DisplayMagician.GameLibraries.GameLibrary|Program/LoadGamesInBackground: GOG not installed.|
2023-02-23 16:09:29.1239|INFO|DisplayMagician.GameLibraries.GameLibrary|Program/LoadGamesInBackground: Loading Installed Epic Games|
2023-02-23 16:09:29.1239|ERROR|DisplayMagician.GameLibraries.EpicLibrary|EpicLibrary/LoadInstalledGames: Couldn't find the manifests for any locally installed games C:\ProgramData\Epic\EpicGamesLauncher\Data\Manifests. There seems to be a problem with your Epic installation.|
2023-02-23 16:09:29.1239|INFO|DisplayMagician.GameLibraries.GameLibrary|Program/LoadGamesInBackground: Cannot load installed Epic Games!|
2023-02-23 16:09:29.1239|INFO|DisplayMagician.GameLibraries.GameLibrary|Program/LoadGamesInBackground: Loaded all Installed Epic Games (found 0)|
2023-02-23 16:09:29.1414|WARN|DisplayMagician.GameLibraries.OriginLibrary|OriginLibrary/LoadInstalledGames: No Origin games installed in the Origin library|
2023-02-23 16:09:29.1414|INFO|DisplayMagician.GameLibraries.GameLibrary|Program/LoadGamesInBackground: Cannot load installed Origin Games!|
2023-02-23 16:09:29.1414|INFO|DisplayMagician.GameLibraries.GameLibrary|Program/LoadGamesInBackground: Loaded all Installed Origin Games (found 0)|
2023-02-23 16:09:29.6044|INFO|DisplayMagician.GameLibraries.SteamLibrary|SteamLibrary/LoadInstalledGames: Found original steam library C:\Program Files (x86)\Steam|
2023-02-23 16:09:29.6044|INFO|DisplayMagician.GameLibraries.SteamLibrary|SteamLibrary/LoadInstalledGames: Found additional steam library E:\Games\Steam in the C:\Program Files (x86)\Steam\steamapps\libraryfolders.vdf VDF file |
2023-02-23 16:09:29.6044|INFO|DisplayMagician.GameLibraries.SteamLibrary|SteamLibrary/LoadInstalledGames: Found additional steam library F:\SteamLibrary in the C:\Program Files (x86)\Steam\steamapps\libraryfolders.vdf VDF file |
2023-02-23 16:09:29.6094|INFO|DisplayMagician.GameLibraries.SteamLibrary|SteamLibrary/LoadInstalledGames: Found additional steam library E:\Games\Steam|
2023-02-23 16:09:29.6094|INFO|DisplayMagician.GameLibraries.SteamLibrary|SteamLibrary/LoadInstalledGames: Found additional steam library F:\SteamLibrary|
2023-02-23 16:09:29.6746|INFO|DisplayMagician.GameLibraries.SteamLibrary|SteamLibrary/LoadInstalledGames: Found 12 installed Steam games|
2023-02-23 16:09:29.6746|INFO|DisplayMagician.GameLibraries.GameLibrary|Program/LoadGamesInBackground: Loaded all Installed Steam Games (found 12)|
2023-02-23 16:09:29.6746|INFO|DisplayMagician.AppLibraries.AppLibrary|AppLibrary/LoadAppsInBackground: Loading Locally Installed Apps|
2023-02-23 16:09:32.5753|WARN|DisplayMagician.ImageUtils|ShortcutItem/GetMeABitmapFromFile: Exception while trying to extract the icon from an *.exe or *.dll using TsudaKageyu.IconExtractor for file F:\Richard Burns Rally\RichardBurnsRally_SSE.exe.|EXCEPTION OCCURRED :System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at TsudaKageyu.IconExtractor.Initialize(String fileName)
   at DisplayMagician.ImageUtils.GetMeAllBitmapsFromFile(String fileNameAndPath) NativeErrorCode: 2;ErrorCode: -2147467259
2023-02-23 16:09:32.6004|WARN|DisplayMagician.ImageUtils|ShortcutItem/GetMeABitmapFromFile: Exception while trying to Split the icon using MintPlayer IconExtractor on file F:\Richard Burns Rally\RichardBurnsRally_SSE.exe! |EXCEPTION OCCURRED :System.IO.FileNotFoundException: File not found
File name: 'f:\richard burns rally\richardburnsrally_sse.exe'
   at MintPlayer.IconUtils.IconExtractor.Split(String filename)
   at DisplayMagician.ImageUtils.GetMeAllBitmapsFromFile(String fileNameAndPath) FileName: f:\richard burns rally\richardburnsrally_sse.exe
2023-02-23 16:09:32.6079|WARN|DisplayMagician.ImageUtils|ShortcutItem/GetMeABitmapFromFile: Exception while trying to extract the icon from an *.exe or *.dll using TsudaKageyu.IconExtractor for file F:\Richard Burns Rally\rsf_launcher\RallySimFans_Launcher.exe.|EXCEPTION OCCURRED :System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at TsudaKageyu.IconExtractor.Initialize(String fileName)
   at DisplayMagician.ImageUtils.GetMeAllBitmapsFromFile(String fileNameAndPath) NativeErrorCode: 2;ErrorCode: -2147467259
2023-02-23 16:09:32.6079|WARN|DisplayMagician.ImageUtils|ShortcutItem/GetMeABitmapFromFile: Exception while trying to Split the icon using MintPlayer IconExtractor on file F:\Richard Burns Rally\rsf_launcher\RallySimFans_Launcher.exe! |EXCEPTION OCCURRED :System.IO.FileNotFoundException: File not found
File name: 'f:\richard burns rally\rsf_launcher\rallysimfans_launcher.exe'
   at MintPlayer.IconUtils.IconExtractor.Split(String filename)
   at DisplayMagician.ImageUtils.GetMeAllBitmapsFromFile(String fileNameAndPath) FileName: f:\richard burns rally\rsf_launcher\rallysimfans_launcher.exe
2023-02-23 16:09:36.3159|WARN|DisplayMagician.ImageUtils|ShortcutItem/GetMeABitmapFromFile: Exception while trying to extract the icon from an *.exe or *.dll using TsudaKageyu.IconExtractor for file C:\Users\****\AppData\Roaming\Microsoft\Installer\{604CC657-16CC-4DE2-8D80-7C67595A20B7}\_1DB3255E0116EFF5C2A7FF.exe.|EXCEPTION OCCURRED :System.ComponentModel.Win32Exception (0x80004005): %1 is not a valid Win32 application
   at TsudaKageyu.IconExtractor.Initialize(String fileName)
   at DisplayMagician.ImageUtils.GetMeAllBitmapsFromFile(String fileNameAndPath) NativeErrorCode: 193;ErrorCode: -2147467259
2023-02-23 16:09:36.3159|WARN|DisplayMagician.ImageUtils|ShortcutItem/GetMeABitmapFromFile: Exception while trying to Split the icon using MintPlayer IconExtractor on file C:\Users\****\AppData\Roaming\Microsoft\Installer\{604CC657-16CC-4DE2-8D80-7C67595A20B7}\_1DB3255E0116EFF5C2A7FF.exe! |EXCEPTION OCCURRED :System.ComponentModel.Win32Exception (0x80004005): Failed to load the icon from disk
   at MintPlayer.IconUtils.IconExtractor.ExtractIconsFromExe(String exeFileName)
   at DisplayMagician.ImageUtils.GetMeAllBitmapsFromFile(String fileNameAndPath) NativeErrorCode: 193;ErrorCode: -2147467259
2023-02-23 16:09:36.3364|WARN|DisplayMagician.ImageUtils|ShortcutItem/GetMeABitmapFromFile: Exception while trying to extract the icon from an *.exe or *.dll using TsudaKageyu.IconExtractor for file C:\Users\****\AppData\Roaming\Microsoft\Installer\{604CC657-16CC-4DE2-8D80-7C67595A20B7}\_E77606FC7744C902E374B8.exe.|EXCEPTION OCCURRED :System.ComponentModel.Win32Exception (0x80004005): %1 is not a valid Win32 application
   at TsudaKageyu.IconExtractor.Initialize(String fileName)
   at DisplayMagician.ImageUtils.GetMeAllBitmapsFromFile(String fileNameAndPath) NativeErrorCode: 193;ErrorCode: -2147467259
2023-02-23 16:09:36.3454|WARN|DisplayMagician.ImageUtils|ShortcutItem/GetMeABitmapFromFile: Exception while trying to Split the icon using MintPlayer IconExtractor on file C:\Users\****\AppData\Roaming\Microsoft\Installer\{604CC657-16CC-4DE2-8D80-7C67595A20B7}\_E77606FC7744C902E374B8.exe! |EXCEPTION OCCURRED :System.ComponentModel.Win32Exception (0x80004005): Failed to load the icon from disk
   at MintPlayer.IconUtils.IconExtractor.ExtractIconsFromExe(String exeFileName)
   at DisplayMagician.ImageUtils.GetMeAllBitmapsFromFile(String fileNameAndPath) NativeErrorCode: 193;ErrorCode: -2147467259
2023-02-23 16:09:38.4796|WARN|DisplayMagician.ImageUtils|ShortcutItem/GetMeABitmapFromFile: Exception while trying to extract the icon from an *.exe or *.dll using TsudaKageyu.IconExtractor for file F:\Program Files\Rockstar Games\Launcher\LauncherPatcher.exe.|EXCEPTION OCCURRED :System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at TsudaKageyu.IconExtractor.Initialize(String fileName)
   at DisplayMagician.ImageUtils.GetMeAllBitmapsFromFile(String fileNameAndPath) NativeErrorCode: 2;ErrorCode: -2147467259
2023-02-23 16:09:38.4796|WARN|DisplayMagician.ImageUtils|ShortcutItem/GetMeABitmapFromFile: Exception while trying to Split the icon using MintPlayer IconExtractor on file F:\Program Files\Rockstar Games\Launcher\LauncherPatcher.exe! |EXCEPTION OCCURRED :System.IO.FileNotFoundException: File not found
File name: 'f:\program files\rockstar games\launcher\launcherpatcher.exe'
   at MintPlayer.IconUtils.IconExtractor.Split(String filename)
   at DisplayMagician.ImageUtils.GetMeAllBitmapsFromFile(String fileNameAndPath) FileName: f:\program files\rockstar games\launcher\launcherpatcher.exe
2023-02-23 16:09:40.1449|INFO|DisplayMagician.AppLibraries.LocalLibrary|LocalLibrary/LoadInstalledApps: Found 180 locally installed Apps|
2023-02-23 16:09:40.1449|INFO|DisplayMagician.AppLibraries.AppLibrary|AppLibrary/LoadAppsInBackground: Loaded all Locally Installed Apps (found 180)|
2023-02-23 16:09:40.2995|ERROR|DisplayMagician.Program|Program/Main general exception during app.Execute(args): |EXCEPTION OCCURRED :System.TypeInitializationException: The type initializer for 'DisplayMagicianShared.AMD.AMDLibrary' threw an exception. ---> System.EntryPointNotFoundException: Unable to find an entry point named 'ADL2_Display_SLSMapConfig_Get' in DLL 'atiadlxx.dll'.
   at System.Runtime.InteropServices.Marshal.InternalPrelink(IRuntimeMethodInfo m)
   at System.Runtime.InteropServices.Marshal.PrelinkAll(Type c)
   at DisplayMagicianShared.AMD.AMDLibrary..ctor()
   at DisplayMagicianShared.AMD.AMDLibrary..cctor()
   --- End of inner exception stack trace ---
   at DisplayMagicianShared.AMD.AMDLibrary.GetLibrary()
   at DisplayMagicianShared.ProfileItem..ctor()
   at DisplayMagicianShared.ProfileRepository.UpdateActiveProfile(Boolean fastScan)
   at DisplayMagicianShared.ProfileRepository.get_CurrentProfile()
   at DisplayMagician.UIForms.MainForm..ctor(Form formToOpen)
   at DisplayMagician.Program.<>c__DisplayClass35_0.<Main>b__5()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<ExecuteAsync>d__154.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at DisplayMagician.Program.Main(String[] args) TypeName: DisplayMagicianShared.AMD.AMDLibrary`

**Comment by mjbarr** [comment]
You can ignore this, I noticed the AMD references at the end of that error and used DDU to uninstall old AMD drivers from my machine and it has started working now :)

**Comment by jcwing01** [comment]
Hi Terry!  I have the same problem here, only DDU does not fix it.  I have an AMD HD 6450 as a secondary card, and the log file exception line reports as follows:

2023-03-02 09:47:23.4215|ERROR|DisplayMagician.Program|Program/Main general exception during app.Execute(args): |EXCEPTION OCCURRED :System.TypeInitializationException: The type initializer for 'DisplayMagicianShared.AMD.AMDLibrary' threw an exception. ---> System.EntryPointNotFoundException: Unable to find an entry point named 'ADL2_Adapter_AdapterInfoX4_Get' in DLL 'atiadlxx.dll'.

Disabling the AMD 6450 driver does not help, but uninstalling it using DDU does allow DM to work until the system restarts (and I assume the dll file loads?'.  Thanks for any help and let me know if you need any other info, this is my first time submitting to a github forum. 

Jay
