### ISSUE TITLE
Error when applying a Profile

### ISSUE THREAD

**Issue by thomprl** [terrymacdonald/DisplayMagician#205]
**Describe the bug**
When selecting a different profile and clicking apply I get the following error message.  The profile seems to apply if I hit the continue button.

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at DisplayMagician.Program.ApplyProfileTask(ProfileItem profile)
   at DisplayMagician.UIForms.DisplayProfileForm.Apply_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4614.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
DisplayMagician
    Assembly Version: 2.5.0.352
    Win32 Version: 2.5.0.352
    CodeBase: file:///E:/Program%20Files/DisplayMagician/DisplayMagician.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
NLog
    Assembly Version: 5.0.0.0
    Win32 Version: 5.1.1.1522
    CodeBase: file:///E:/Program%20Files/DisplayMagician/NLog.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
DisplayMagician.Shared
    Assembly Version: 2.4.2.0
    Win32 Version: 2.4.2.0
    CodeBase: file:///E:/Program%20Files/DisplayMagician/DisplayMagician.Shared.DLL
----------------------------------------
McMaster.Extensions.CommandLineUtils
    Assembly Version: 4.0.2.0
    Win32 Version: 4.0.2.0
    CodeBase: file:///E:/Program%20Files/DisplayMagician/McMaster.Extensions.CommandLineUtils.DLL
----------------------------------------
Microsoft.Toolkit.Uwp.Notifications
    Assembly Version: 7.1.0.0
    Win32 Version: 7.1.3.1
    CodeBase: file:///E:/Program%20Files/DisplayMagician/Microsoft.Toolkit.Uwp.Notifications.DLL
----------------------------------------
Windows.ApplicationModel
    Assembly Version: 255.255.255.255
    Win32 Version: 10.0.10011.16384
    CodeBase: file:///C:/Windows/system32/WinMetadata/Windows.ApplicationModel.winmd
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
Windows.Foundation
    Assembly Version: 255.255.255.255
    Win32 Version: 10.0.10011.16384
    CodeBase: file:///C:/Windows/system32/WinMetadata/Windows.Foundation.winmd
----------------------------------------
System.Runtime.WindowsRuntime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.WindowsRuntime/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.WindowsRuntime.dll
----------------------------------------
Windows.Storage
    Assembly Version: 255.255.255.255
    Win32 Version: 10.0.10011.16384
    CodeBase: file:///C:/Windows/system32/WinMetadata/Windows.Storage.winmd
----------------------------------------
DynamicComActivator
    Assembly Version: 0.0.0.0
    Win32 Version: 7.1.3.1
    CodeBase: file:///E:/Program%20Files/DisplayMagician/Microsoft.Toolkit.Uwp.Notifications.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.2.27524
    CodeBase: file:///E:/Program%20Files/DisplayMagician/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4584.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
AudioSwitcher.AudioApi.CoreAudio
    Assembly Version: 4.0.0.308
    Win32 Version: 4.0.0.308
    CodeBase: file:///E:/Program%20Files/DisplayMagician/AudioSwitcher.AudioApi.CoreAudio.DLL
----------------------------------------
AudioSwitcher.AudioApi
    Assembly Version: 4.0.0.308
    Win32 Version: 4.0.0.308
    CodeBase: file:///E:/Program%20Files/DisplayMagician/AudioSwitcher.AudioApi.DLL
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices.RuntimeInformation/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
PInvokeDelegateFactoryInternalAssembly
    Assembly Version: 0.0.0.0
    Win32 Version: 2.4.2.0
    CodeBase: file:///E:/Program%20Files/DisplayMagician/DisplayMagician.Shared.dll
----------------------------------------
EDIDParser
    Assembly Version: 1.2.5.3
    Win32 Version: 1.2.5.3
    CodeBase: file:///E:/Program%20Files/DisplayMagician/EDIDParser.DLL
----------------------------------------
ImageListView
    Assembly Version: 13.8.2.0
    Win32 Version: 13.8.2.0
    CodeBase: file:///E:/Program%20Files/DisplayMagician/ImageListView.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4614.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
IconLib
    Assembly Version: 0.73.0.0
    Win32 Version: 0.73.0.0
    CodeBase: file:///E:/Program%20Files/DisplayMagician/IconLib.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

```

**Comment by terrymacdonald** [comment]
Hi @thomprl

Firstly, does the error happen reliably - so every time?? If so, which
Display Profile is the one that is causing the error?  Or are all of them?

Can you please also create a Support ZIP File so that I can see what errors
are in the logs:

   - Open up DisplayMagician and click on the Settings button
   - Change the logging level to TRACE
   - Go and do whatever you need to in order to make the error happen
   - Once you have made the error happen, go back into the Settings area
   and click on the Create Support ZIP File button.
   - Save the ZIP file that is created to your computer.
   - Visit the GitHub issue win your web browser, and then upload the
   Support ZIP File using your web browser (do not attach the file to this
   email as it doesn't work)

Once I get that Support ZIP File I'll take a look and see what I can see in
the logs.

Thanks
Terry

**Comment by terrymacdonald** [comment]
Hi @thomprl ,

I'll close this issue for now as you haven't responded. Please feel free to upload the Support ZIP File anytime through your web browser and I will then reopen this issue and take a look at it.

Thanks
Terry
