### ISSUE TITLE
App generates an unhandled exception when exiting the Settings window

### ISSUE THREAD

**Issue by NudeNULL** [terrymacdonald/DisplayMagician#359]
**Describe the bug**
App generates an unhandled exception when exiting the settings window.
The top part of the error:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at DisplayMagician.UIForms.SettingsForm.SettingsForm_FormClosing(Object sender, FormClosingEventArgs e)
   at System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Private.CoreLib.dll
----------------------------------------
DisplayMagician
    Assembly Version: 2.7.0.0
    Location: 
----------------------------------------
System.Runtime
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Runtime.dll
----------------------------------------
NLog
    Assembly Version: 5.0.0.0
    Location: 
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\netstandard.dll
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\Microsoft.Win32.Registry.dll
----------------------------------------
DisplayMagician.Shared
    Assembly Version: 2.7.0.0
    Location: 
----------------------------------------
System.Threading.Thread
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Threading.Thread.dll
----------------------------------------
McMaster.Extensions.CommandLineUtils
    Assembly Version: 4.1.1.0
    Location: 
----------------------------------------
System.Net.Http
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Net.Http.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.7\System.Windows.Forms.dll
----------------------------------------
System.Console
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Console.dll
----------------------------------------
System.Net.ServicePoint
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Net.ServicePoint.dll
----------------------------------------
System.Net.Security
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Net.Security.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.ComponentModel.dll
----------------------------------------
Microsoft.Toolkit.Uwp.Notifications
    Assembly Version: 7.1.0.0
    Location: 
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.7\System.Windows.Forms.Primitives.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Collections.Specialized.dll
----------------------------------------
System.Collections
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Collections.dll
----------------------------------------
System.Threading
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Settings
2. Click Back
3. A popup appears (screenshot attached)

**Expected behaviour**
It should not generate an exception and exit the settings window successfully

**Screenshots**
![image](https://github.com/user-attachments/assets/dd4761c4-ff80-4a98-aa10-8aea71799f33)

**Reporting Logs**
[DisplayMagician-Support-20241222-1016.zip](https://github.com/user-attachments/files/18221513/DisplayMagician-Support-20241222-1016.zip)

**Enviroment (please complete the following information):**
 - Windows Version: Win 11
 - DisplayMagician Version 2.7.2.1
 - Number and Type of Video Cards: Gigabyte RTX 3080Ti Extreme
 - Number and make/model of displays: 2x Acer VG270U
 - How displays are conencted (and if any adapters being used): Both using the HDMI ports
 - Video Card driver version: NVIDIA GeForce Game Ready Driver v566.36
 - Have you run Windows Update?: Yes

**Additional context**
This issue could be related to my other bug report related to saving the setting to start the app minimized
Also, in older versions, like 2.6.x.x, it was working, I have updated to this version because I couldn't save the fact that it should not bother me every time I start PC that an update is present.

**Comment by terrymacdonald** [comment]
The error appears to be related to a missing program setting entry, which is weird as your settings in your Settings.json file are absolutely valid and accurate. I'm not sure how you're getting this error when the file looks perfect. What language are you currently running on your PC?

I've performed testing the program settings form and code and I cannot get this same error to occur.  I've tried with a config from an earlier version of DisplayMagician, and with a brand new install. I'm not sure why you are seeing this problem and I am not. It could be a problem with a previous upgrade that hasn't patched the config file properly? Or maybe an issue with a different user language? I'm not sure at the moment.

A workaround will be probably be best in your instance. We can force DisplayMagician to create a new settings file (and it will keep your display profiles and your game shortcuts). To do this:

- Close/Exit DisplayMagician so it is not running.
- Navigate to `C:\Users\<username>\AppData\Local\DisplayMagician` and rename the `Settings.json` file to `Settings.json.old`. This will allow us to revert this workaround if this doesn't work.
- Restart DisplayMagician.

DisplayMagician should now start ok and it will have the default settings. Feel free to make any changes to any settings you want, and see if everything works now.

Please report back here to tell me if everything is working ok. I will keep this issue open until I hear from you.

Thanks
Terry

**Comment by NudeNULL** [comment]
Hi, thanks for your support!

After doing these steps, I do not receive the exceptions anymore.
Here are the files that were in that folder from appdata
![image](https://github.com/user-attachments/assets/37bcb728-10c6-40cf-b15c-5ad70ad8e1d8)

and the Settings files, all 4 of them, just in case you want to check what could be the reason.
[DisplayMagician.zip](https://github.com/user-attachments/files/18306248/DisplayMagician.zip)
